version: '3.7'

services:
  app:
    container_name: demo_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_URI=http://10.83.30.52:8088/rest/